name: remy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-326.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dots_indicator: ^3.0.0

  # localization
  easy_localization: ^3.0.2
  # Routing
  go_router: ^8.0.5

  # DI
  get_it: ^7.6.0
  injectable: ^2.1.2

  # Modeling
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1

  # State management
  equatable: ^2.0.3
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1

  #client
  dio: ^5.3.0

  # dev
  dartz: ^0.10.1
  intl: ^0.18.0
  tuple: ^2.0.1
  logger: ^1.3.0
  fpdart: ^0.5.0

  #ui
  flutter_screenutil: ^5.7.0
  carousel_slider: ^4.2.1
  flutter_form_builder: ^9.1.0
  cupertino_tabbar:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  bloc_test: ^9.1.1

  fluttertoast: ^8.2.4
flutter:


  uses-material-design: true











  fonts:
    - family: Noor Regular
      fonts:
        - asset: assets/fonts/Noor Regular.ttf
    - family: Noor Bold
      fonts:
        - asset: assets/fonts/Noor_Bold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/launcher_icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21